server:
  port: 8082
  servlet:
    context-path: /kkx
    tomcat:
      uri-encoding: utf-8

count: ${age}

spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
